[package]
name = "chatclient"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version = "0.13.1", features=["advanced"]}
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
aes = "0.8.4"
base64 = "0.22.1"
